/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package partner.java.sdk.client.demo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test void appHasAMain() {
    //     App classUnderTest = new App();
    //     assertNotNull(classUnderTest.main(), "app should have a main");
    // }
}
