/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package partner.java.sdk.client.demo;

import jp.pokepay.partnerapi.request.SendEcho;
import jp.pokepay.partnerapi.response.Echo;
import jp.pokepay.partnerapi.request.Request;
import jp.pokepay.partnerapi.PartnerAPI;
import java.io.File;

public class App {
    public static void main(String[] args) {
        try {
            jp.pokepay.partnerapi.PartnerAPI client = new jp.pokepay.partnerapi.PartnerAPI(new File("/home/wiz/.pokepay/config.properties"));
            Request request = new SendEcho("Hello");
            Echo echo = (Echo) client.send(request);
            System.out.println(echo.getStatus());
            System.out.println(echo.getMessage());
        } catch (jp.pokepay.partnerapi.PartnerRequestError error) {
            System.out.println(error.getType());
            System.out.println(error.getMessage());
            System.out.println(error.getRawJson());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}

// public class App {
//     public String getGreeting() {
//         return "Hello World!";
//     }

//     public static void main(String[] args) {
//         System.out.println(new App().getGreeting());
//     }
// }
